### ISSUE TITLE
Routing fails on linux(fedora)

### ISSUE THREAD

**Issue by mantesat** [felixguendling/osrm-backend#1]
I've re-built the latest code, but still getting server errors:

[warn] [server error] code: vector::_M_range_check, uri: /multitarget?loc=35.153034,33.343548&loc=34.920845,33.614044&loc=34.920845,33.614044

or 

[warn] [server error] code: vector::_M_range_check, uri: /viaroute?loc=35.153034,33.343548&loc=34.920845,33.614044&loc=34.920845,33.614044

I\m still noticing some capital/non-capital letter directories (algorithms, benchmarks, contractor, extractor)

**Comment by felixguendling** [comment]
Seems like the branch I pushed was somehow messed up.

I created a new version based on the master branch (OSRM version 4.5.0).
The latest commit (https://github.com/felixguendling/osrm-backend/commit/f4b9b866c124575d684be18a8332aa1eb38a28c2) is the minimal set of changes required for the new functionality.

I commited the change to the master branch of this repository and removed the old feature branch.

I have tried this on my desktop machine running Fedora. It should look like this:

    ➜  build git:(master) ./osrm-routed map/hessen-latest.osrm
    [warn] ./osrm-routed could not be locked to RAM
    [info] starting up engines, v4.5.0
    [info] populating base path: map/hessen-latest.osrm
    [info] HSGR file:   "map/hessen-latest.osrm.hsgr"
    [info] loading graph data
    [info] loading graph from map/hessen-latest.osrm.hsgr
    [info] number_of_nodes: 860208, number_of_edges: 4030050
    [info] loaded 860208 nodes and 4030050 edges
    [info] Data checksum is 3815329157
    [info] loading edge information
    [info] loading geometries
    [info] loading r-tree
    [info] loading timestamp
    [info] Loading Timestamp
    [info] loading street names
    [info] loaded plugin: table
    [info] loaded plugin: hello
    [info] loaded plugin: locate
    [info] loaded plugin: multitarget
    [info] loaded plugin: multisource
    [info] loaded plugin: nearest
    [info] loaded plugin: timestamp
    [info] loaded plugin: viaroute
    [info] http 1.1 compression handled by zlib version 1.2.8
    [info] running and waiting for requests
    [info] 02-03-2015 21:08:42 127.0.0.1 - Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/38.0.2125.122 Safari/537.36 /multitarget?loc=49.872825,8.651193&loc=50.1109221,8.6821267
    [info] 02-03-2015 21:08:42 127.0.0.1 - Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/38.0.2125.122 Safari/537.36 /favicon.ico

The JSON response looks like this:

    {"distances":[{"distance":34372.553182,"time_cost":1791}]}

**Comment by mantesat** [comment]
It works! I'll put it in a more production environment and I'll keep you informed. It seems fast, even as a temporary solution it should be included in the official OSRM repo.

Thanks!

**Comment by felixguendling** [comment]
Great to hear it's working! Thanks for testing the code. For my tests, this method did yield the same results as table-routing (modified to calculate only one row/column) but was ~2x faster. Feel free to report any further issues you find here.
I don't expect to see this in the OSRM main repository. The changes to support N:1/1:N are only 387 additions and 6 deletions (according to the commit) and are quite modular. It would be easy to integrate this but obviously they are only interested in N:M. This would be nice but currently, I don't have a use-case for this. Thus, I won't be the one to implement this at the moment.
